FROM node:22-alpine AS build
WORKDIR /web
COPY frontend/package.json /web/package.json
RUN npm install
COPY frontend /web
RUN npm run build

FROM nginx:1.27-alpine
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /web/dist /usr/share/nginx/html
